# npm 빌드를 위한 node 설치
FROM node:14.17.1-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:${PATH}
COPY package*.json ./
RUN yarn install
COPY . ./
COPY .env ./
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]